config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  resources :tasks  # new create show delete edit update tasks

  resources :goals
  resources :users

get '/', to: 'sessions#new'
get '/login', to: 'sessions#new'
post '/login', to: 'sessions#create'
get '/signup', to: 'users#new'
delete '/logout', to: 'sessions#destroy'

end

# Not needed:
# resources :goal_categories
# resources :categories

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :goals

  def goal_count
    self.goals.count
  end

end

app/models/goal.rb
class Goal < ApplicationRecord
  has_many :tasks
  has_and_belongs_to_many :categories
  belongs_to :user

  validates :goal_name , presence: true

  def goal_tasks
    puts self.tasks
  end

  def task_count
    self.tasks.count
  end

end

app/models/goal_category.rb
class GoalCategory < ApplicationRecord
  belongs_to :goal
  belongs_to :category
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :goal

  validates :date, :task_name, :duration, presence: true




end

app/models/user.rb
class User < ApplicationRecord
  has_many :goals
  has_many :tasks, through: :goals

  validates :first_name, :last_name, presence: true
  validates :email, uniqueness: true, presence: true

  has_secure_password

  def full_name
    "#{self.first_name} #{self.last_name}"
  end

  def user_goals
    goals = self.goals
  end

  def user_task_info
    task_info = self.tasks.map {|t| [t.date, t.task_name]}
    task_info.sort
    #this returns an array of task arrays for the specified user sorted by date
  end




end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :logged_in? 

  def current_user
    if session[:user_id]
      @user = User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    !!current_user
  end

  def authorized
    redirect_to login_path unless logged_in?
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:edit, :update, :destroy]
  # before_action :require_login
    #
    # def index
    #   @categories = Category.all
    # end

    def new
      if !!flash[:data]
        @category = Category.new(flash[:data])
      else
        @category = Category.new
      end
    end

    def create
     @category= Category.create(category_params)
     if @category.valid?
       redirect_to category_path(@category)
     else
       flash[:errors] = @category.errors.full_messages
       flash[:data] = category_params
       redirect_to login_path
     end
    end

    # def show
    # end

    def edit
    end

    def update
      if @category.update(category_params)
       redirect_to category_path(@category)
      else
       flash[:errors] = @category.errors.full_messages
       flash[:data] = category_params
       redirect_to edit_category_path
      end
    end

    def destroy
      @category.destroy
      redirect_to categories_path
    end

    private

    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:goal_type)
    end

end

app/controllers/goal_categories_controller.rb
class GoalCategoriesController < ApplicationController


end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
    before_action :set_goal, only: [:show, :edit, :update, :destroy]

  def index
      @goals = current_user.goals
  end

  def new
    @goal = Goal.new
  end

  def create
    @user = User.find(session[:user_id])
    @goal= Goal.new(goal_params)
    @goal.user_id = @user.id
    if @goal.valid?
      @goal.save
      redirect_to user_path(@goal.user)
    else
      flash[:errors] = @goal.errors.full_messages
      flash[:data] = goal_params
      redirect_to new_goal_path
    end
  end

  def show
  end

  def edit
  end

  def update
    if @goal.update(goal_params)
     redirect_to user_path(@goal.user)
    else
     flash[:errors] = @goal.errors.full_messages
     flash[:data] = goal_params
     redirect_to edit_goal_path
    end
  end

  def destroy
    @goal.destroy
    redirect_to user_path(@goal.user)
  end

  private

  def set_goal
    @goal = Goal.find(params[:id])
  end

  def goal_params
    params.require(:goal).permit(:goal_name, :frequency, :duration, :category_name, category_ids: [])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def login
  end

  def create
      @user = User.find_by(email: params[:email])
      if !!@user && @user.authenticate(params[:password])
        session[:user_id] = @user.id
        redirect_to @user
      else
      redirect_to login_path
    end
  end

  def destroy
    session.delete (:user_id)
    redirect_to login_path
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # before_action :authorized

  def index
    @tasks = Task.all
  end

  def new
    @user = User.find(session[:user_id])
    @goals = @user.goals
    @task = Task.new
  end

  def create
   @task= Task.create(task_params)
    if @task.valid?
     redirect_to task_path(@task)
    else
     flash[:errors] = @task.errors.full_messages
     flash[:data] = task_params
     redirect_to new_task_path
    end
  end

  def show
    @goals = Goal.all
    @user = @task.goal.user
  end

  def edit
    @goals = Goal.all
  end

  def update
    if @task.update(task_params)
     redirect_to task_path(@task)
    else
     flash[:errors] = @task.errors.full_messages
     flash[:data] = task_params
     redirect_to edit_task_path
    end
  end

  def destroy
    @task.destroy
    redirect_to user_path(@task.goal.user)
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:task_name,:goal_id, :completed, :date,:duration)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

    def index
      @users = User.all
    end

    def new
      if !!flash[:data]
        @user = User.new(flash[:data])
      else
        @user = User.new
      end
    end

    def create
     @user = User.create(user_params)
      if @user.valid?
       redirect_to login_path
      else
       flash[:errors] = @user.errors.full_messages
       flash[:data] = user_params
       redirect_to login_path
      end
    end

    def show
      @goals = Goal.all
    end

    def edit
    end

    def update
      if @user.update(user_params)
       redirect_to user_path(@user)
      else
       flash[:errors] = @user.errors.full_messages
       flash[:data] = user_params
       redirect_to edit_user_path
      end
    end

    def destroy
      @user.destroy
      redirect_to users_path
    end

    private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :photo)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/goal_categories_helper.rb
module GoalCategoriesHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/goals/_form.erb
  <% if !!flash[:errors]%>
    <% flash[:errors].each do |error| %>
    <p> <%= error %> </p>
    <%end%>
  <%end%>

  <!-- @goal.categories << category -->


  <body>
    <div class="form-group">
    <p><%= form_for @goal do |f| %></p>
    <div class="field form-group">
      <%= f.label "Category" %><br />
      <%= f.collection_check_boxes :category_ids, Category.all, :id, :goal_type do |b| %>
        <div class="collection-check-box">
          <%= b.check_box %>
          <%= b.label %>
        </div>
      <% end %>
    </div>
    <p><%= f.label "Goal Name" %></p>
    <p><%= f.text_area :goal_name %></p>
    <p><%= f.label "Times per week" %></p>
    <p><%= f.text_field :frequency%>
    <p><%= f.label "Duration - (minutes)" %></p>
    <p><%= f.text_field :duration %></p>
    <p><%= f.submit %></p>
    <%end%>
    </div>
  </body>

app/views/goals/edit.erb
<html class= "usershow">

  <head>
    <link href="https://fonts.googleapis.com/css?family=Fjalla+One" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Faster+One" rel="stylesheet">

    <style>
      a{
        color:white;
      }
      body{
        background-color:black;
        color:white;
        opacity: .8;
        padding-left: 5%;
        padding-right: 30%;
        font-family: 'Fjalla One', sans-serif;
        letter-spacing: .5px;
        position: relative;
        top: 5px;
        bottom:60px;
        right:100px;
        left:20px;
        font-size: 25px;
      }
      span{
        font-size: 80px;
        background-color:black;
      }
    </style>
  </head>

  <body>
<h1>Edit this goal</h1>

<%= render 'form' %>
</body>
</html>

app/views/goals/index.erb
<h1>Your Goals</h1>
  <body>
  <p> <% @goals.each do |goal|%> </p>
  <p><b>Goal:</b> <%= link_to goal.goal_name, goal %> </p>
  <%end%><br>
  <p> <%= link_to "Make a new goal", new_goal_path %> </p>

  <p> <%= link_to "See users", users_path %> </p>

</body>

app/views/goals/new.erb
<html class= "usershow">

  <head>
    <link href="https://fonts.googleapis.com/css?family=Fjalla+One" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Faster+One" rel="stylesheet">

      <style>
          body{
              font-family: 'Fjalla One', sans-serif;
              letter-spacing: .5px;
              position: relative;
              top: 5px;
              bottom:60px;
              right:100px;
              left:20px;
              color:white;
              font-size: 25px;
              background-color:black;
              opacity: .8;
              padding: 20px;
            }
          a{
            color:white;
          }
          span{
            font-size: 80px;
            background-color:black;
          }
      </style>
  </head>
  <body>

  <h1> Make a New Goal</h1>

  <%= render 'form' %>
</body>
</html>

app/views/goals/show.erb
  <html class= "usershow">

    <head>
      <link href="https://fonts.googleapis.com/css?family=Fjalla+One" rel="stylesheet">
      <link href="https://fonts.googleapis.com/css?family=Faster+One" rel="stylesheet">

      <style>
        a{
          color:white;
        }
        body{
          background-color:black;
          color:white;
          opacity: .8;
          padding-left: 5%;
          padding-right: 30%;
          font-family: 'Fjalla One', sans-serif;
          letter-spacing: .5px;
          position: relative;
          top: 5px;
          bottom:60px;
          right:100px;
          left:20px;
          font-size: 25px;
        }
        span{
          font-size: 80px;
          background-color:black;
        }
      </style>
    </head>

  <br><span id = "strive" >STRIVE</span><br>

  <body>
    <h3> <b>Goal: </b><%= @goal.goal_name%> </h3>
    <h5>Goal Categories:<% @goal.categories.each do |c|%></h5>
    <li><%=c.goal_type %></li>
    <%end%><hr>

    <h5>To accomplish this goal you must complete the following: </h5>
    <%@goal.tasks.each do |task|%>
    <li> <%=link_to task.task_name.capitalize, task %><br></li>
    <%end%>

    <h5>Schedule a workout below!</h5>
    <p><%= link_to "Schedule a workout", new_task_path%></p>
  </body>
  <hr>
  <p><%= link_to "Edit Goal", edit_goal_path(@goal)%></p>
  <p><%= link_to "Go back to your goals", user_path(@goal.user) %></p>
  <button class="ui black button"><%= button_to "Delete Goal", goal_path(@goal), method: "delete"%></button>
  </html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Strive</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <h7>
    <% if logged_in? %>
      <%= link_to "Logout", logout_path, method: :delete %>
    <% end %>
    <%= yield %>
  </h7>
  <body>

  </body>

</html>

app/views/tasks/_form.erb
<% if !!flash[:errors]%>
<% flash[:errors].each do |error| %>
<p> <%= error %> </p>
<%end%>
<%end%>

<body>
<p><%= form_for @task do |f| %></p>
<p><%= f.label "Workout Name" %></p>
<p><%= f.text_area :task_name %></p>
<p><%= f.label "Select Goal" %></p>
<p><%= f.collection_select :goal_id , @goals, :id , :goal_name %></p>
<p><%= f.label :completed %></p>
<p><%= f.check_box :completed %></p>
<p><%= f.label :date %></p>
<p><%= f.date_field :date%></p>
<p><%= f.label :duration %></p>
<p><%= f.text_field :duration %></p>
<p><%= f.submit %></p>
<%end%>
</body>

app/views/tasks/edit.erb
<body>
<h1>Edit this Task</h1>

<%= render 'form' %>
</body>

app/views/tasks/index.erb
<h1>Your Tasks</h1>

  <body>

  <p> <% @tasks.each do |t|%> </p>
  <p> Task: <%=link_to t.task_name, t%> </p>
  <%end%>
  <br>

  <p> <%= link_to "Make a new task", new_task_path %> </p>

</body>

app/views/tasks/new.erb
<html class= "usershow">

  <head>
    <link href="https://fonts.googleapis.com/css?family=Fjalla+One" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Faster+One" rel="stylesheet">

      <style>
          body{
              font-family: 'Fjalla One', sans-serif;
              letter-spacing: .5px;
              position: relative;
              top: 5px;
              bottom:60px;
              right:100px;
              left:20px;
              color:white;
              font-size: 25px;
              background-color:black;
              opacity: .8;
              padding: 20px;
            }
          a{
            color:white;
          }
          span{
            font-size: 80px;
            background-color:black;
          }
      </style>
  </head>

<body>

  <h1> STRIVE </h1>
  <h4> Add a workout</h4>
  <%= render 'form' %>

</body>
</html>

app/views/tasks/show.erb
<html class= "usershow">

  <head>
    <link href="https://fonts.googleapis.com/css?family=Fjalla+One" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Faster+One" rel="stylesheet">

      <style>
          body{
              font-family: 'Fjalla One', sans-serif;
              letter-spacing: .5px;
              position: relative;
              top: 5px;
              bottom:60px;
              right:100px;
              left:20px;
              color:white;
              font-size: 25px;
              background-color:black;
              opacity: .8;
            }
          a{
            color:white;
          }
          span{
            font-size: 80px;
            background-color:black;
          }
      </style>
  </head>

<h1>About this Task</h1>
  <body>
  <p> <b>Task: </b><%= @task.task_name %> </p>
  <p> <b>Date:<b> <%= @task.date.strftime("%b %d, %Y")%> </p>
  <p> <b>Completed? </b>: <%= @task.completed%> </p>

  <p><%= link_to "Edit Task", edit_task_path(@task)%></p>
  <p><%= link_to "Home Page", user_path(@user) %></p>
  <button class="ui black button"><%= button_to "Delete Task", task_path(@task), method: "delete"%></button>

</body>
</html>

app/views/users/_form.erb
<% if !!flash[:errors]%>
<% flash[:errors].each do |error| %>
<p> <%= error %> </p>
<%end%>
<%end%>

<!-- LOGIN  -->

<div>
    <p><%= form_for(@user) do |f|%></p>
      <p><%= f.label :first_name %></p>
      <p><%= f.text_field :first_name %></p>
      <p><%= f.label :last_name %></p>
      <p><%= f.text_field :last_name %></p>
      <p><%= f.label :email %></p>
      <p><%= f.email_field :email %></p>
      <p><%= f.label :password %></p>
      <p><%= f.password_field :password %></p>
      <p><%= f.label :password_confirmation, "Confirmation" %></p>
      <p><%= f.password_field :password_confirmation %></p>
      <p><%= f.submit "Create my account" %></p>
    <% end %>
</div>

app/views/users/edit.erb
<html class= "usershow">

  <head>
    <link href="https://fonts.googleapis.com/css?family=Fjalla+One" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Faster+One" rel="stylesheet">

      <style>
          body{
              font-family: 'Fjalla One', sans-serif;
              letter-spacing: .5px;
              position: relative;
              top: 5px;
              bottom:60px;
              right:100px;
              left:20px;
              color:white;
              font-size: 25px;
              background-color:black;
              opacity: .8;
              padding: 20px;
            }
          a{
            color:white;
          }
          span{
            font-size: 80px;
            background-color:black;
          }
      </style>
  </head>
    <body>
<h1>Edit this User</h1>

<%= render 'form' %>
</body>
</html>

app/views/users/index.erb
<h1> Users </h1>

  <body>
    <p> <% @users.each do |user|%> </p>
    <p><b>User:</b> <%= link_to "#{user.first_name} #{user.last_name}", user %> </p>
    <%end%><br>

    <p> <%= link_to "Sign Up Now!", signup_path %> </p>
  </body>

app/views/users/new.erb
<html class= "usershow">

  <head>
    <link href="https://fonts.googleapis.com/css?family=Fjalla+One" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Faster+One" rel="stylesheet">

      <style>
          body{
              font-family: 'Fjalla One', sans-serif;
              letter-spacing: .5px;
              position: relative;
              top: 5px;
              bottom:60px;
              right:100px;
              left:20px;
              color:white;
              font-size: 20px;
              background-color:black;
              opacity: .8;
              padding-left: 20px;
              padding-bottom: 10px;

            }
          a{
            color:white;
          }
          span{
            font-size: 80px;
            background-color:black;
          }
      </style>
  </head>

<br><span id = "strive" >STRIVE</span><br>

<body>
<h1>Sign Up Now!</h1>

<%= render 'form' %>
</body>
</html>

app/views/users/show.erb
<html class= "usershow">

  <head>
    <link href="https://fonts.googleapis.com/css?family=Fjalla+One" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Faster+One" rel="stylesheet">

      <style>
          body{
              font-family: 'Fjalla One', sans-serif;
              letter-spacing: .5px;
              position: relative;
              top: 5px;
              bottom:60px;
              right:100px;
              left:20px;
              color:white;
              font-size: 25px;
            }
          a{
            color:white;
          }
          span{
            font-size: 80px;
            background-color:black;
          }
      </style>
  </head>

  <!--USER GOAL INFO -->

  <br><span id = "strive" >STRIVE</span><br>

  <h2 class = "welcome" >Welcome back, <%= @user.first_name %>! </h2><br>
  <div class="user">
      <body>
        <h3> Your Fitness Goals </h3>
        <%@user.goals.each do |g|%>
        <ul><li><%=link_to g.goal_name, g %></li></ul>
        <%end%>
      <p><%= link_to "Make a new goal!", new_goal_path(@user) %></p><hr>
  </div>

  <!--USER GOAL INFO -->

  <div id="usergoals">
    <h3>Upcoming Workouts</h3>
      <%@user.user_task_info.each do |task|%>
      <li><%= "#{task[1]}: #{task[0].strftime("%b %d, %Y")}" %></li>
      <% end %><hr>
  </div>

  <!--PROFILE INFO -->

    <div class = "profile">
      <h4>Profile Info</h4>
      <p> <b>User Name: </b><%= "#{@user.first_name} #{@user.last_name}" %> </p>
      <p> <b>User Email: </b><%= @user.email %> </p>

      <p><%= link_to "Edit My Account", edit_user_path(@user)%></p>
      <button class="ui black button"><%= button_to "Delete My Account", user_path(@user), method: "delete"%></button>
    </div><br>

  </body><br>

</html>